query GovernedGroupsQueryJob($id: ID!) {
    governedGroupsQueryJob(jobId: $id) {
        jobId
        jobStatus
        jobProgress
        results {
            group {
                id
                samAccountName
                directoryServices {
                    name
                    id
                }
            }
            isBypass
            isGoverned
            owners {
                id
                samAccountName
            }
            authorizers {
                level
            }
        }
    }
}
