query {
  identitiesAsync(
    where: {
      privilegeddentityType: { in: ADMIN }
      type: { eq: USER }
      passwordExpirationStatus: { eq: NEVER_EXPIRES }
    }
  ) {
    jobId
    jobStatus
    results {
      name
      directoryServices {
        directoryType {
          name
        }
      }
      affiliation
      privilegedIdentityType
      expirationStatus
      isDisabled
      lastLogonTime
    }
  }
}
